name: Wheel builder

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: pp* *-musllinux_* *-manylinux_i686 *-win32  # skip PyPy, musllinux, 32-bit Linux & win32 builds
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: wheelhouse/*.whl

  package_source:
    name: Package source distribution
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build
        run: python -m pip install build

      - name: Run sdist
        run: python -m build --sdist

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: ./dist/*.tar.gz

  retrieve_build_files:
    name: Retrieve build files
    needs:
      - build_wheels
      - package_source
    runs-on: ubuntu-22.04

    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: List files
        run: |
          pwd
          ls -hog dist